[pytest]
addopts = -v -n auto --html=report/report.html --self-contained-html
testpaths = testcase
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: mark a test as a smoke test.
    regression: mark a test as a regression test.
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S

# 测试报告中的日志配置
log_level = INFO
log_format = %(asctime)s | %(levelname)-8s | %(name)s:%(funcName)s:%(lineno)d - %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
